// ═══════════════════════════════════════════════════════════
//  EMAGRECIMENTO BLINDADO — 30 CARROSSÉIS × 10 CARDS
//  Layout: 60% foto (top) + 40% texto (bottom)
// ═══════════════════════════════════════════════════════════

const CARROSSEIS = [

// ─────────────────────────────────────────────────────────
//  MANHÃ 01-10 · HULK BLINDADO · Motivacional
// ─────────────────────────────────────────────────────────

{
  id: '01', tipo: 'manha',
  nome: 'Levanta, você ainda não terminou sua história',
  legenda: 'Você está lendo isso porque ainda não desistiu. 💪\n\nIsso já diz tudo sobre quem você é.\n\nSalva esse post e lê quando precisar de força.\n\n#emagrecimentoblindado',
  hashtags: '#emagrecimentoblindado #motivacaofeminina #forcainterior #recomecar #hulkblindado',
  cards: [
    { titulo: 'LEVANTA.', subtitulo: 'Você ainda não terminou sua história.' },
    { titulo: 'Todo dia você acorda', subtitulo: 'carregando o peso de quem tentou e não viu resultado.' },
    { titulo: 'Mas você ainda está aqui.', subtitulo: 'Isso já diz muito sobre quem você é.' },
    { titulo: 'Perfeição não existe.', subtitulo: 'O que existe é a decisão de continuar, mesmo imperfeita.' },
    { titulo: 'Não espere se sentir pronta.', subtitulo: 'Comece do jeito que você está agora.' },
    { titulo: 'Cada pequeno passo conta.', subtitulo: 'Mesmo os que parecem insignificantes.' },
    { titulo: 'Você não precisa voltar ao passado.', subtitulo: 'Você precisa se tornar quem ainda vai ser.' },
    { titulo: 'Cair faz parte.', subtitulo: 'O que define você é quantas vezes se levantou.' },
    { titulo: 'A virada não precisa ser grande.', subtitulo: 'Ela precisa ser real. E começa agora.' },
    { titulo: '💾 Salva esse post.', subtitulo: 'Lê sempre que precisar de força.', cta: true },
  ],
},

{
  id: '02', tipo: 'manha',
  nome: 'Hoje você não precisa ser perfeita, só precisa continuar',
  legenda: 'A perfeição é a maior armadilha que existe. 💛\n\nVocê não precisa ser perfeita hoje.\nSó precisa continuar.\n\nSalva esse post pra quem precisa ouvir isso.',
  hashtags: '#naodesista #forcafeminina #emagrecimentoblindado #recomecar #motivacao',
  cards: [
    { titulo: 'HOJE', subtitulo: 'Você não precisa ser perfeita. Só precisa continuar.' },
    { titulo: 'A perfeição é uma armadilha.', subtitulo: 'Ela te paralisa quando você mais precisa agir.' },
    { titulo: 'Comeu errado ontem?', subtitulo: 'Não importa. Hoje é um dia novo.' },
    { titulo: 'Passou uma semana sem fazer nada?', subtitulo: 'Tudo bem. Você está recomeçando agora.' },
    { titulo: 'Progresso não é linha reta.', subtitulo: 'É uma curva com altos, baixos e recomeços.' },
    { titulo: 'A mulher que chega', subtitulo: 'é a que não desiste, não a que nunca tropeça.' },
    { titulo: 'Imperfeita e em movimento', subtitulo: 'vale mais do que perfeita e parada.' },
    { titulo: 'Não espere o momento certo.', subtitulo: 'Crie o momento certo com o que você tem.' },
    { titulo: 'Continuar, mesmo com vontade de parar,', subtitulo: 'é o maior ato de força que existe.' },
    { titulo: '💾 Salva pra lembrar.', subtitulo: 'Você vai precisar ler isso de novo.', cta: true },
  ],
},

{
  id: '03', tipo: 'manha',
  nome: 'O peso que mais te trava não está só na balança',
  legenda: 'O peso que mais pesa não aparece na balança. 🌸\n\nÉ o peso do julgamento. Da vergonha. Do "e se não funcionar?"\n\nComenta aqui: qual peso você quer largar hoje?',
  hashtags: '#autoperdao #autoestimafeminina #emagrecimentoblindado #libertacao #forcainterna',
  cards: [
    { titulo: 'O PESO QUE MAIS TE TRAVA', subtitulo: 'não está só na balança.' },
    { titulo: 'Tem o peso da vergonha.', subtitulo: 'De se olhar no espelho e não gostar do que vê.' },
    { titulo: 'Tem o peso do julgamento.', subtitulo: 'Do que os outros pensam. Do que você mesma pensa.' },
    { titulo: 'Tem o peso do "e se não funcionar?"', subtitulo: 'O medo de tentar e falhar de novo.' },
    { titulo: 'Esse peso é invisível.', subtitulo: 'Mas é o que mais pesa no dia a dia.' },
    { titulo: 'Nenhuma dieta elimina', subtitulo: 'o peso emocional que te impede de avançar.' },
    { titulo: 'Antes de mudar o corpo,', subtitulo: 'é preciso parar de se punir por ter esse corpo.' },
    { titulo: 'Você merece cuidado.', subtitulo: 'Não punição. Não vergonha. Cuidado.' },
    { titulo: 'Largar esse peso', subtitulo: 'é o primeiro passo para qualquer transformação real.' },
    { titulo: '💾 Salva esse card.', subtitulo: 'E compartilha com quem precisa ouvir.', cta: true },
  ],
},

{
  id: '04', tipo: 'manha',
  nome: 'Pare de esperar motivação para começar',
  legenda: 'Motivação não aparece antes de começar. Ela aparece depois. 🔥\n\nComece sem ela. A força vem no caminho.\n\nSalva esse post pra quando a preguiça vier forte.',
  hashtags: '#disciplina #emagrecimentoblindado #comigoate o fim #acao #motivacaodiaria',
  cards: [
    { titulo: 'PARE DE ESPERAR MOTIVAÇÃO', subtitulo: 'para começar.' },
    { titulo: 'Motivação não aparece primeiro.', subtitulo: 'Ela aparece depois que você age.' },
    { titulo: 'Esperar se sentir motivada', subtitulo: 'é esperar algo que raramente chega na hora certa.' },
    { titulo: 'Disciplina não é força de vontade.', subtitulo: 'É criar um ambiente que facilita suas escolhas.' },
    { titulo: 'Não espere a segunda-feira.', subtitulo: 'Não espere o dia 1. Não espere estar pronta.' },
    { titulo: 'Comece pequeno.', subtitulo: 'Uma escolha melhor hoje já é um começo.' },
    { titulo: 'A ação cria a motivação.', subtitulo: 'Nunca o contrário.' },
    { titulo: 'Você não precisa querer.', subtitulo: 'Você precisa decidir.' },
    { titulo: 'A força não vem antes de começar.', subtitulo: 'Ela vem porque você começou.' },
    { titulo: '💾 Salva isso.', subtitulo: 'Lê quando a preguiça vier forte.', cta: true },
  ],
},

{
  id: '05', tipo: 'manha',
  nome: 'Um dia ruim não destrói seu progresso',
  legenda: 'Um dia ruim NÃO destrói meses de progresso. 💪\n\nMas desistir sim.\n\nNão deixa um dia ruim virar uma semana ruim.',
  hashtags: '#persistencia #emagrecimentoblindado #naodesista #transformacao #mindset',
  cards: [
    { titulo: 'UM DIA RUIM', subtitulo: 'não destrói seu progresso.' },
    { titulo: 'Um deslize não apaga', subtitulo: 'dias, semanas ou meses de esforço.' },
    { titulo: 'O problema não é escorregar.', subtitulo: 'O problema é não se levantar.' },
    { titulo: 'Comeu tudo que não devia?', subtitulo: 'Tudo bem. A próxima refeição é um recomeço.' },
    { titulo: 'Não foi pra academia essa semana?', subtitulo: 'Amanhã você pode retomar sem drama.' },
    { titulo: 'O ciclo da culpa', subtitulo: 'é mais prejudicial do que qualquer deslize.' },
    { titulo: 'Uma rachadura na parede', subtitulo: 'não derruba a casa.' },
    { titulo: 'Se punir não corrige nada.', subtitulo: 'Recomeçar com gentileza, sim.' },
    { titulo: 'Um dia ruim vira problema', subtitulo: 'só quando você deixa ele virar uma semana.' },
    { titulo: '💾 Salva esse post.', subtitulo: 'E lê no próximo dia difícil.', cta: true },
  ],
},

{
  id: '06', tipo: 'manha',
  nome: 'Você já venceu dias piores',
  legenda: 'Pensa no que você já superou na vida. 🌸\n\nDias muito piores do que esse.\n\nE você está aqui. Isso é prova de que você consegue.',
  hashtags: '#voceconsegue #forcafeminina #emagrecimentoblindado #superacao #autoestima',
  cards: [
    { titulo: 'VOCÊ JÁ VENCEU', subtitulo: 'dias muito piores do que esse.' },
    { titulo: 'Pensa no que você já superou.', subtitulo: 'Situações que pareciam impossíveis de aguentar.' },
    { titulo: 'E você está aqui.', subtitulo: 'Em pé. Resistindo. Tentando de novo.' },
    { titulo: 'Isso não é fraqueza.', subtitulo: 'É uma das formas mais silenciosas de coragem.' },
    { titulo: 'Você já enfrentou dores maiores', subtitulo: 'do que uma dieta que não funcionou.' },
    { titulo: 'E se você conseguiu antes,', subtitulo: 'você consegue de novo. Com mais sabedoria.' },
    { titulo: 'A mulher que você é hoje', subtitulo: 'foi construída por cada dia difícil que você sobreviveu.' },
    { titulo: 'Não subestime sua força.', subtitulo: 'Ela é maior do que você imagina.' },
    { titulo: 'Hoje pode ser difícil.', subtitulo: 'Mas você já venceu coisa muito pior.' },
    { titulo: '💾 Salva esse post.', subtitulo: 'E manda para alguém que está lutando.', cta: true },
  ],
},

{
  id: '07', tipo: 'manha',
  nome: 'Seu corpo precisa de cuidado, não de castigo',
  legenda: 'Toda vez que você restringe demais, pula refeição ou se pune por comer "errado"...\n\nVocê está enviando ao seu corpo uma mensagem de guerra. 🌸\n\nSeu corpo não é seu inimigo.',
  hashtags: '#cuidadocorporal #emagrecimentoblindado #semculpa #autocompaixao #saude',
  cards: [
    { titulo: 'SEU CORPO PRECISA', subtitulo: 'de cuidado. Não de castigo.' },
    { titulo: 'Cada vez que você restringe demais,', subtitulo: 'você ensina seu corpo a desconfiar de você.' },
    { titulo: 'Cada vez que pula refeição', subtitulo: 'por punição, o metabolismo se protege.' },
    { titulo: 'Seu corpo não é seu inimigo.', subtitulo: 'Ele tenta sobreviver às ordens que você dá.' },
    { titulo: 'Dieta de castigo', subtitulo: 'nunca foi e nunca será o caminho.' },
    { titulo: 'Comer com culpa', subtitulo: 'é mais prejudicial do que o que você come.' },
    { titulo: 'Cuidar do corpo é nutri-lo,', subtitulo: 'movê-lo com prazer, ouvi-lo quando pede descanso.' },
    { titulo: 'Você não precisa ganhar o direito', subtitulo: 'de comer. Você precisa comer para viver bem.' },
    { titulo: 'Mude a relação.', subtitulo: 'De guerra para cuidado. Isso muda tudo.' },
    { titulo: '💾 Salva esse card.', subtitulo: 'Seu corpo te agradecer.', cta: true },
  ],
},

{
  id: '08', tipo: 'manha',
  nome: 'Recomeçar também é força',
  legenda: 'Tem pessoas que acham que recomeçar é sinal de fraqueza. Eu acho o contrário. 💛\n\nRecomeçar tantas vezes quanto for preciso — isso é força.\n\nComenta: quantas vezes você já recomeçou?',
  hashtags: '#recomecar #forcainterior #emagrecimentoblindado #naoapague #transformacao',
  cards: [
    { titulo: 'RECOMEÇAR', subtitulo: 'também é força.' },
    { titulo: 'Não é fraqueza começar de novo.', subtitulo: 'É inteligência reconhecer que precisa de uma nova direção.' },
    { titulo: 'Toda mulher que transformou a vida', subtitulo: 'recomeçou várias vezes antes de chegar lá.' },
    { titulo: 'O erro não é cair.', subtitulo: 'O erro é achar que caiu faz de você um fracasso.' },
    { titulo: 'Cada recomeço traz aprendizado.', subtitulo: 'Você não está no mesmo lugar. Está mais sábia.' },
    { titulo: 'Não apague seus recomeços.', subtitulo: 'Eles fazem parte da sua história.' },
    { titulo: 'A mulher mais forte que você conhece', subtitulo: 'provavelmente já caiu mais vezes do que você imagina.' },
    { titulo: 'Recomeçar não é voltar ao início.', subtitulo: 'É avançar com mais experiência.' },
    { titulo: 'Então recomeça.', subtitulo: 'Quantas vezes for preciso. Sem vergonha.' },
    { titulo: '💾 Salva esse post.', subtitulo: 'Compartilha com quem precisa ouvir isso.', cta: true },
  ],
},

{
  id: '09', tipo: 'manha',
  nome: 'A mulher que você quer ser precisa da sua decisão hoje',
  legenda: 'A mulher que você quer ser está esperando uma decisão sua. 🌸\n\nNão amanhã. Não na segunda-feira. Hoje.\n\nQue decisão você vai tomar agora?',
  hashtags: '#decisao #transformacaofeminina #emagrecimentoblindado #futura #comece',
  cards: [
    { titulo: 'A MULHER QUE VOCÊ QUER SER', subtitulo: 'precisa da sua decisão hoje.' },
    { titulo: 'Ela não está esperando a segunda-feira.', subtitulo: 'Ela está esperando que você decida agora.' },
    { titulo: 'Não amanhã.', subtitulo: 'Não quando a vida ficar mais fácil. Hoje.' },
    { titulo: 'Decisões pequenas', subtitulo: 'constroem transformações grandes.' },
    { titulo: 'Você não precisa mudar tudo de uma vez.', subtitulo: 'Precisa mudar uma coisa hoje.' },
    { titulo: 'A versão futura de você', subtitulo: 'é construída pelas escolhas da versão atual.' },
    { titulo: 'Ela quer se sentir leve.', subtitulo: 'Ela quer se olhar no espelho com orgulho.' },
    { titulo: 'Ela precisa que você tome', subtitulo: 'uma decisão diferente agora.' },
    { titulo: 'O melhor momento para começar', subtitulo: 'foi há meses. O segundo melhor é agora.' },
    { titulo: '💾 Salva esse post.', subtitulo: 'E toma uma pequena decisão hoje.', cta: true },
  ],
},

{
  id: '10', tipo: 'manha',
  nome: 'Não deixe a vergonha mandar na sua vida',
  legenda: 'A vergonha te isola. Te paralisa. Te faz evitar fotos, praias, reuniões. 💔\n\nMas a vergonha não precisa ser o fim da história.\n\nComenta aqui: o que a vergonha já te impediu de fazer?',
  hashtags: '#semvergonha #autoestima #emagrecimentoblindado #libertacao #coragem',
  cards: [
    { titulo: 'NÃO DEIXE A VERGONHA', subtitulo: 'mandar na sua vida.' },
    { titulo: 'A vergonha te faz evitar fotos.', subtitulo: 'Te faz recusar convites. Te faz se esconder.' },
    { titulo: 'Te faz escolher roupas', subtitulo: 'para esconder em vez de para se sentir bonita.' },
    { titulo: 'A vergonha paralisa.', subtitulo: 'E quem está parada não consegue avançar.' },
    { titulo: 'Mas a vergonha é uma mentira.', subtitulo: 'Ela diz que você não merece ocupar espaço.' },
    { titulo: 'Você merece ocupar espaço.', subtitulo: 'Do tamanho que você está agora.' },
    { titulo: 'Seu valor não é definido', subtitulo: 'pelo número que aparece na balança.' },
    { titulo: 'A vergonha nunca motivou ninguém', subtitulo: 'de verdade. Ela só paralisa.' },
    { titulo: 'Deixa a vergonha ir.', subtitulo: 'E começa a cuidar de você com respeito.' },
    { titulo: '💾 Salva esse post.', subtitulo: 'E manda pra quem está se escondendo da vida.', cta: true },
  ],
},

// ─────────────────────────────────────────────────────────
//  CONTEÚDO 11-20 · Educativo + Identificação
// ─────────────────────────────────────────────────────────

{
  id: '11', tipo: 'conteudo',
  nome: 'Por que você não emagrece como aos 20 anos',
  legenda: 'Com 20 anos você comia qualquer coisa e ficava bem.\nHoje parece que engorda olhando pra comida. 😔\n\nIsso não é fraqueza. É fisiologia. Vem entender.\n\nSalva esse post — é explicação que vale ouro.',
  hashtags: '#metabolismo #hormoniofeminino #emagrecimentoblindado #depois40 #saude',
  cards: [
    { titulo: 'POR QUE VOCÊ NÃO EMAGRECE', subtitulo: 'como emagrecia aos 20 anos?' },
    { titulo: 'Não é preguiça.', subtitulo: 'Não é falta de esforço. É biologia.' },
    { titulo: 'Depois dos 35,', subtitulo: 'os hormônios mudam. O metabolismo muda. O corpo muda.' },
    { titulo: 'Estrogênio caindo', subtitulo: 'afeta diretamente onde e como o corpo guarda gordura.' },
    { titulo: 'Cortisol elevado', subtitulo: 'por estresse e privação de sono retém gordura abdominal.' },
    { titulo: 'O que funcionava antes', subtitulo: 'pode ser exatamente o que sabota você hoje.' },
    { titulo: 'Comer menos e se exercitar mais', subtitulo: 'pode piorar tudo quando os hormônios estão fora do ponto.' },
    { titulo: 'Seu corpo precisa de estratégia,', subtitulo: 'não de punição.' },
    { titulo: 'A solução não é a mesma de antes.', subtitulo: 'Porque você não é a mesma de antes.' },
    { titulo: 'Quer entender a estratégia certa?\n\nComente', subtitulo: 'BLINDADO', cta: true, pill: true },
  ],
},

{
  id: '12', tipo: 'conteudo',
  nome: 'Comer pouco nem sempre é o caminho',
  legenda: 'Você corta tudo, passa fome, e mesmo assim não emagrece?\n\nIsso tem explicação. E a solução não é comer menos ainda. 🥗\n\nSalva esse post — pode mudar tudo.',
  hashtags: '#restricaocalorica #metabolismo #emagrecimentoblindado #comerbem #estrategia',
  cards: [
    { titulo: 'COMER POUCO', subtitulo: 'nem sempre é o caminho.' },
    { titulo: 'Você corta tudo.', subtitulo: 'Passa fome. Fica irritada. E a balança não mexe.' },
    { titulo: 'Isso tem um motivo.', subtitulo: 'Restrição severa ativa o modo de sobrevivência no corpo.' },
    { titulo: 'Com menos comida,', subtitulo: 'o metabolismo desacelera para preservar energia.' },
    { titulo: 'Você queima menos.', subtitulo: 'Ganha mais. E sente mais fome do que nunca.' },
    { titulo: 'Não é falta de força de vontade.', subtitulo: 'É o seu corpo fazendo exatamente o que foi programado.' },
    { titulo: 'A solução não é comer ainda menos.', subtitulo: 'É comer melhor. Na hora certa. Do jeito certo.' },
    { titulo: 'Proteína de manhã.', subtitulo: 'Refeições regulares. Sono de qualidade. Estresse menor.' },
    { titulo: 'Isso não é moda.', subtitulo: 'É o que a fisiologia feminina pede.' },
    { titulo: 'Quer o método completo?\n\nComente', subtitulo: 'BLINDADO', cta: true, pill: true },
  ],
},

{
  id: '13', tipo: 'conteudo',
  nome: 'Não é falta de força de vontade',
  legenda: 'Pare de se culpar por comer o que não devia. 🧠\n\nA fome que você sente às 16h não é fraqueza. É cortisol.\nO que você come à noite não é gula. É serotonina baixa.\n\nSalva isso. É importante.',
  hashtags: '#hormoniofeminino #cortisol #emagrecimentoblindado #semculpa #ciencia',
  cards: [
    { titulo: 'NÃO É FALTA DE FORÇA DE VONTADE.', subtitulo: 'É hormônio.' },
    { titulo: 'A fome que bate às 16h todo dia?', subtitulo: 'Cortisol elevado por estresse crônico.' },
    { titulo: 'Comer tudo à noite depois de passar o dia inteiro "na linha"?', subtitulo: 'Serotonina baixa. O corpo busca carboidrato para compensar.' },
    { titulo: 'Ansiedade que só melhora quando come?', subtitulo: 'Dopamina e cortisol fora do equilíbrio.' },
    { titulo: 'Acordar com fome mesmo tendo jantado?', subtitulo: 'Insulina desregulada durante o sono.' },
    { titulo: 'Nenhum desses é fraqueza.', subtitulo: 'São sinais do que precisa ser ajustado no seu sistema.' },
    { titulo: 'Força de vontade não regula hormônio.', subtitulo: 'Estratégia regula.' },
    { titulo: 'Quando os hormônios estão em equilíbrio,', subtitulo: 'a fome diminui. A ansiedade reduz. O corpo responde.' },
    { titulo: 'Você não precisa de mais força.', subtitulo: 'Você precisa da informação certa.' },
    { titulo: 'Quer essa informação?\n\nComente', subtitulo: 'BLINDADO', cta: true, pill: true },
  ],
},

{
  id: '14', tipo: 'conteudo',
  nome: 'O ciclo da culpa alimentar',
  legenda: 'Restrict → Compulsão → Culpa → Restrição → Compulsão...\n\nVocê conhece esse ciclo? 😔\n\nNão é fraqueza. É o ciclo que qualquer pessoa entra quando a dieta é o erro.',
  hashtags: '#cicloculpa #relacaocomida #emagrecimentoblindado #alimentacaoconsciente #saude',
  cards: [
    { titulo: 'O CICLO DA CULPA ALIMENTAR', subtitulo: 'e por que você fica presa nele.' },
    { titulo: 'Começa com restrição.', subtitulo: 'Você corta tudo. Dieta rígida. Regras severas.' },
    { titulo: 'Aí vem a compulsão.', subtitulo: 'Um dia difícil. Um evento. Uma emoção. Você come demais.' },
    { titulo: 'Depois vem a culpa.', subtitulo: '"Estraguei tudo. Não tenho vergonha. Não consigo."' },
    { titulo: 'A culpa leva a mais restrição.', subtitulo: '"Agora vou compensar." E o ciclo recomeça.' },
    { titulo: 'Esse ciclo não é fraqueza.', subtitulo: 'É a consequência inevitável de qualquer dieta muito restritiva.' },
    { titulo: 'Quanto mais você restringe,', subtitulo: 'mais forte fica o gatilho para a compulsão.' },
    { titulo: 'A saída não é mais força de vontade.', subtitulo: 'É quebrar o ciclo com uma abordagem diferente.' },
    { titulo: 'Quando você para de proibir,', subtitulo: 'a compulsão perde o poder sobre você.' },
    { titulo: 'Quer aprender a sair desse ciclo?\n\nComente', subtitulo: 'BLINDADO', cta: true, pill: true },
  ],
},

{
  id: '15', tipo: 'conteudo',
  nome: 'O que muda no corpo depois dos 40',
  legenda: 'Depois dos 40, o jogo muda. E ninguém te avisou. 😔\n\nO que funcionava antes pode ser exatamente o que sabota você hoje.\n\nSalva esse post — é informação que muda tudo.',
  hashtags: '#depois40 #hormoniofeminino #emagrecimentoblindado #menopausa #metabolismo',
  cards: [
    { titulo: 'O QUE MUDA NO CORPO', subtitulo: 'depois dos 40 — e ninguém te contou.' },
    { titulo: 'O metabolismo desacelera.', subtitulo: 'Você queima menos calorias em repouso do que antes.' },
    { titulo: 'O estrogênio cai.', subtitulo: 'A gordura começa a se depositar no abdômen em vez do quadril.' },
    { titulo: 'O sono piora.', subtitulo: 'E privação de sono eleva cortisol e aumenta a fome.' },
    { titulo: 'A massa muscular diminui.', subtitulo: 'E menos músculo significa metabolismo ainda mais lento.' },
    { titulo: 'A insulina fica menos eficiente.', subtitulo: 'Carboidrato que antes era neutro passa a virar gordura.' },
    { titulo: 'Isso não é destino.', subtitulo: 'É um mapa. E mapa você pode seguir com a estratégia certa.' },
    { titulo: 'A mulher de 40+ pode emagrecer sim.', subtitulo: 'Mas precisa de uma abordagem diferente da mulher de 25.' },
    { titulo: 'Conhecer o seu corpo é o começo', subtitulo: 'de parar de lutar contra ele.' },
    { titulo: 'Quer a estratégia para esse corpo?\n\nComente', subtitulo: 'BLINDADO', cta: true, pill: true },
  ],
},

{
  id: '16', tipo: 'conteudo',
  nome: 'Por que a roupa apertada mexe tanto com você',
  legenda: 'Não é frescura. Não é vaidade. É muito mais profundo do que isso. 💔\n\nA roupa que não fecha mexe com a sua identidade.\n\nComenta aqui: você já deixou de fazer algo por causa disso?',
  hashtags: '#imagemcorporal #autoestima #emagrecimentoblindado #roupas #identidade',
  cards: [
    { titulo: 'POR QUE A ROUPA APERTADA', subtitulo: 'mexe tanto com você?' },
    { titulo: 'Não é frescura.', subtitulo: 'Não é vaidade superficial.' },
    { titulo: 'Roupa é identidade.', subtitulo: 'É como você se apresenta para o mundo.' },
    { titulo: 'Quando a roupa não fecha,', subtitulo: 'a mensagem que o cérebro recebe é: "eu perdi o controle."' },
    { titulo: 'Isso afeta como você entra em um ambiente.', subtitulo: 'Como você se senta. Como você fala. Como você se sente.' },
    { titulo: 'Mulheres evitam eventos,', subtitulo: 'praias, fotos e reuniões por causa disso.' },
    { titulo: 'Não é frescura.', subtitulo: 'É a vida sendo afetada por algo que parece pequeno mas não é.' },
    { titulo: 'Você merece se vestir', subtitulo: 'com algo que te faça sentir bem. Não se esconder.' },
    { titulo: 'E isso é possível.', subtitulo: 'Sem dieta maluca. Sem passar fome.' },
    { titulo: 'Quer saber como?\n\nComente', subtitulo: 'BLINDADO', cta: true, pill: true },
  ],
},

{
  id: '17', tipo: 'conteudo',
  nome: 'O que acontece quando você se abandona',
  legenda: 'Cuidar de todo mundo e esquecer de si mesma.\n\nIsso tem um nome: autoabandono. E o corpo cobra. 💔\n\nComenta aqui: você cuida de todo mundo antes de cuidar de você?',
  hashtags: '#autocuidado #autoabandono #emagrecimentoblindado #mulheres #prioridade',
  cards: [
    { titulo: 'O QUE ACONTECE', subtitulo: 'quando você se abandona.' },
    { titulo: 'Filhos, trabalho, casa, marido.', subtitulo: 'Você cuida de todo mundo. Menos de você.' },
    { titulo: 'No começo parece normal.', subtitulo: 'Depois vira um hábito. Depois vira identidade.' },
    { titulo: 'E aí o corpo começa a falar.', subtitulo: 'Peso, cansaço, dor, insatisfação.' },
    { titulo: 'Não é falta de tempo.', subtitulo: 'É que você colocou o seu cuidado em último lugar por tanto tempo que parece natural.' },
    { titulo: 'Mas não é.', subtitulo: 'Você também merece atenção. Do seu próprio tempo e energia.' },
    { titulo: 'Cuidar de você', subtitulo: 'não é egoísmo. É necessidade.' },
    { titulo: 'Uma mulher esgotada', subtitulo: 'não consegue cuidar bem de ninguém por muito tempo.' },
    { titulo: 'Colocar você na lista', subtitulo: 'é o primeiro passo para mudar qualquer coisa.' },
    { titulo: 'Quer dar esse primeiro passo?\n\nComente', subtitulo: 'BLINDADO', cta: true, pill: true },
  ],
},

{
  id: '18', tipo: 'conteudo',
  nome: 'Por que você recomeça toda segunda-feira',
  legenda: '"Na segunda eu começo." Você já disse isso?\n\nA segunda-feira virou um ritual de punição disfarçado de recomeço. 😔\n\nSalva esse post e lê. Vai fazer sentido.',
  hashtags: '#segundafeira #ciclodieta #emagrecimentoblindado #recomecar #mude',
  cards: [
    { titulo: '"NA SEGUNDA EU COMEÇO."', subtitulo: 'Por que você sempre volta para esse ponto?' },
    { titulo: 'A semana começa com restrição.', subtitulo: 'Tudo controlado, rígido, sem margem.' },
    { titulo: 'No fim de semana a pressão alivia.', subtitulo: 'E vem a compensação. Come tudo que ficou sem.' },
    { titulo: 'Aí vem a culpa.', subtitulo: '"Estraguei. Começo de novo na segunda."' },
    { titulo: 'E o ciclo reinicia.', subtitulo: 'Segunda após segunda. Mês após mês. Ano após ano.' },
    { titulo: 'A segunda-feira virou um ritual', subtitulo: 'de autopunição disfarçado de esperança.' },
    { titulo: 'Mas a solução não é uma dieta mais rígida.', subtitulo: 'É uma abordagem que não precise de segunda-feira.' },
    { titulo: 'Quando não há privação,', subtitulo: 'não há compulsão de fim de semana.' },
    { titulo: 'E quando não há compulsão,', subtitulo: 'a segunda-feira vira um dia normal.' },
    { titulo: 'Quer sair desse ciclo de vez?\n\nComente', subtitulo: 'BLINDADO', cta: true, pill: true },
  ],
},

{
  id: '19', tipo: 'conteudo',
  nome: 'Como a vergonha atrapalha sua rotina',
  legenda: 'A vergonha não te motiva. Ela te paralisa. 😔\n\nE quanto mais você espera "melhorar" para viver, mais a vida passa.\n\nComenta aqui: o que você deixou de fazer por vergonha?',
  hashtags: '#vergonha #autoestima #emagrecimentoblindado #libertacao #semparalisia',
  cards: [
    { titulo: 'COMO A VERGONHA', subtitulo: 'atrapalha sua rotina.' },
    { titulo: 'Você evita a academia', subtitulo: 'porque não quer ser vista do jeito que está.' },
    { titulo: 'Você evita praias, piscinas,', subtitulo: 'festas, fotos, roupas que você amava.' },
    { titulo: 'Você espera "melhorar"', subtitulo: 'para começar a viver.' },
    { titulo: 'Mas enquanto espera,', subtitulo: 'o tempo passa. E a vida também.' },
    { titulo: 'A vergonha não te motiva.', subtitulo: 'Ela te congela no lugar.' },
    { titulo: 'E o pior:', subtitulo: 'quanto mais você espera, mais distante parece a mudança.' },
    { titulo: 'Não é preciso chegar lá para começar.', subtitulo: 'É preciso começar para poder chegar.' },
    { titulo: 'Você merece viver agora.', subtitulo: 'Com o corpo que você tem hoje.' },
    { titulo: 'Quer dar esse primeiro passo?\n\nComente', subtitulo: 'BLINDADO', cta: true, pill: true },
  ],
},

{
  id: '20', tipo: 'conteudo',
  nome: 'O erro de tentar compensar tudo depois',
  legenda: '"Hoje comi errado. Amanhã compenso com jejum."\n\nIsso parece lógico. Mas é exatamente o que mantém o ciclo. 😔\n\nSalva esse post — pode mudar sua relação com comida.',
  hashtags: '#compensacao #ciclodieta #emagrecimentoblindado #equilibrio #relacaocomida',
  cards: [
    { titulo: 'O ERRO DE TENTAR', subtitulo: 'compensar tudo depois.' },
    { titulo: '"Hoje comi demais.', subtitulo: 'Amanhã fico sem comer."' },
    { titulo: '"Esse fim de semana saí da dieta.', subtitulo: 'Na segunda começo com jejum e academia todos os dias."' },
    { titulo: 'Parece lógico.', subtitulo: 'Mas é exatamente o que mantém o ciclo.' },
    { titulo: 'Compensação extrema', subtitulo: 'gera mais restrição. Mais restrição gera mais compulsão.' },
    { titulo: 'O corpo não funciona', subtitulo: 'como uma conta bancária que você pode zerar e recomeçar.' },
    { titulo: 'O que ele entende é:', subtitulo: '"Ciclo de escassez. Preciso guardar mais gordura."' },
    { titulo: 'A resposta não é a compensação.', subtitulo: 'É o equilíbrio que o corpo não precisa fugir.' },
    { titulo: 'Um dia ruim não apaga nada.', subtitulo: 'A próxima refeição é só a próxima refeição.' },
    { titulo: 'Quer aprender a sair desse ciclo?\n\nComente', subtitulo: 'BLINDADO', cta: true, pill: true },
  ],
},

// ─────────────────────────────────────────────────────────
//  CTA 21-30 · Noite · CTA para Grupo VIP
// ─────────────────────────────────────────────────────────

{
  id: '21', tipo: 'cta',
  nome: 'Cansada de recomeçar toda segunda-feira?',
  legenda: 'Se você chegou até aqui, esse post foi pra você. ❤️\n\nChega de segunda-feira. Chega de recomeço sem fim.\n\nComente BLINDADO e entre para o Grupo VIP.',
  hashtags: '#emagrecimentoblindado #grupovip #cansada #recomecar #mudancadevida',
  cards: [
    { titulo: 'CANSADA DE RECOMEÇAR', subtitulo: 'toda segunda-feira?' },
    { titulo: 'Já foram meses assim.', subtitulo: 'Talvez anos.' },
    { titulo: 'Começa animada.', subtitulo: 'Dura semanas. Para. Recomeça.' },
    { titulo: 'E a frustração acumula', subtitulo: 'a cada ciclo que se repete.' },
    { titulo: 'Você não é fraca.', subtitulo: 'Você está usando um método que não foi feito para o seu corpo.' },
    { titulo: 'Existe uma forma diferente.', subtitulo: 'Sem dieta maluca. Sem passar fome. Sem segunda-feira.' },
    { titulo: 'Mulheres que encontraram esse caminho', subtitulo: 'pararam de contar os dias para poder comer.' },
    { titulo: 'Isso é possível.', subtitulo: 'E está mais perto do que você imagina.' },
    { titulo: 'Você não precisa fazer isso sozinha.', subtitulo: 'Existe um grupo esperando por você.' },
    { titulo: 'Comente BLINDADO', subtitulo: 'e entre para o Grupo VIP gratuito agora.', cta: true, pill: true },
  ],
},

{
  id: '22', tipo: 'cta',
  nome: 'Quantas roupas você deixou de usar?',
  legenda: 'Aquele vestido no fundo do armário que você não usa faz anos. 👗\n\nVocê sabe do que estou falando.\n\nChega. Comente BLINDADO e entra no Grupo VIP.',
  hashtags: '#roupas #armario #emagrecimentoblindado #grupovip #mudanca',
  cards: [
    { titulo: 'QUANTAS ROUPAS', subtitulo: 'você deixou de usar?' },
    { titulo: 'Aquele vestido no fundo do armário.', subtitulo: 'Que você não usa faz dois, três, quatro anos.' },
    { titulo: 'As calças que ficaram pequenas.', subtitulo: 'Que você guarda "para quando emagrecer."' },
    { titulo: 'As blusas que ficaram apertadas', subtitulo: 'e você não tem coragem de jogar fora.' },
    { titulo: 'Cada peça dessas', subtitulo: 'é um lembrete diário de como você se sente.' },
    { titulo: 'Você merece se vestir', subtitulo: 'com algo que te faça sentir bem agora.' },
    { titulo: 'Não depois de emagrecer.', subtitulo: 'Não quando chegar no peso ideal. Agora.' },
    { titulo: 'E sim, existe um jeito de chegar lá.', subtitulo: 'Sem punição. Sem dieta impossível.' },
    { titulo: 'Esse armário pode mudar.', subtitulo: 'E você também.' },
    { titulo: 'Comente BLINDADO', subtitulo: 'e entre para o Grupo VIP gratuito.', cta: true, pill: true },
  ],
},

{
  id: '23', tipo: 'cta',
  nome: 'Quantas fotos você evitou tirar?',
  legenda: 'Quantas memórias você deixou de registrar porque não queria aparecer nas fotos? 📸\n\nIsso dói.\n\nComente BLINDADO. Chega de se esconder.',
  hashtags: '#fotos #memorias #emagrecimentoblindado #grupovip #autoestima',
  cards: [
    { titulo: 'QUANTAS FOTOS', subtitulo: 'você evitou tirar?' },
    { titulo: 'Eventos que você foi,', subtitulo: 'mas ficou longe das fotos.' },
    { titulo: 'Viagens com a família', subtitulo: 'onde você era sempre quem segurava a câmera.' },
    { titulo: 'Momentos com os filhos', subtitulo: 'que ficaram registrados sem você.' },
    { titulo: 'Aniversários, formaturas, festas.', subtitulo: 'Memórias que você não tem porque não queria aparecer.' },
    { titulo: 'Isso dói.', subtitulo: 'Mais do que qualquer dieta.' },
    { titulo: 'Você merece estar nas memórias.', subtitulo: 'Não atrás da câmera. Na foto.' },
    { titulo: 'Isso não é sobre vaidade.', subtitulo: 'É sobre existir plenamente na sua própria vida.' },
    { titulo: 'Chega de se esconder.', subtitulo: 'Você merece aparecer.' },
    { titulo: 'Comente BLINDADO', subtitulo: 'e entre para o Grupo VIP gratuito.', cta: true, pill: true },
  ],
},

{
  id: '24', tipo: 'cta',
  nome: 'Quantas vezes prometeu que agora seria diferente?',
  legenda: '"Dessa vez vai ser diferente." Quantas vezes você já disse isso? 😔\n\nEu sei. E eu sei que você ainda acredita que pode mudar.\n\nComente BLINDADO. Dessa vez com método.',
  hashtags: '#promessa #mudanca #emagrecimentoblindado #grupovip #recomecar',
  cards: [
    { titulo: 'QUANTAS VEZES VOCÊ PROMETEU', subtitulo: '"que dessa vez seria diferente?"' },
    { titulo: '"Dessa vez vou até o fim."', subtitulo: '"Dessa vez não vou desistir."' },
    { titulo: '"Dessa vez vou me comprometer de verdade."', subtitulo: 'E no começo era verdade.' },
    { titulo: 'Você tentou.', subtitulo: 'Com força de vontade. Com esperança. Com determinação.' },
    { titulo: 'Mas o método falhou.', subtitulo: 'E você levou a culpa.' },
    { titulo: 'Não é você que não funciona.', subtitulo: 'É o método que não foi feito para o seu momento de vida.' },
    { titulo: 'Uma promessa diferente exige', subtitulo: 'uma abordagem diferente.' },
    { titulo: 'Não mais força de vontade sozinha.', subtitulo: 'Estratégia. Suporte. Método.' },
    { titulo: 'Essa vez pode ser diferente.', subtitulo: 'Mas precisa ser com o caminho certo.' },
    { titulo: 'Comente BLINDADO', subtitulo: 'e entre para o Grupo VIP gratuito.', cta: true, pill: true },
  ],
},

{
  id: '25', tipo: 'cta',
  nome: 'Você não precisa passar por isso sozinha',
  legenda: 'Carregar esse peso sozinha é pesado demais. ❤️\n\nExiste um grupo de mulheres que estão no mesmo caminho que você.\n\nComente BLINDADO e venha.',
  hashtags: '#comunidade #apoio #emagrecimentoblindado #grupovip #juntas',
  cards: [
    { titulo: 'VOCÊ NÃO PRECISA', subtitulo: 'passar por isso sozinha.' },
    { titulo: 'Carregar essa frustração sozinha', subtitulo: 'é pesado demais.' },
    { titulo: 'A culpa, o recomeço,', subtitulo: 'o cansaço de tentar sem ver resultado.' },
    { titulo: 'Quando você está sozinha,', subtitulo: 'é fácil achar que o problema é você.' },
    { titulo: 'Mas quando você vê outras mulheres', subtitulo: 'sentindo exatamente o mesmo, tudo muda.' },
    { titulo: 'Existe um grupo', subtitulo: 'de mulheres que estão no mesmo caminho que você.' },
    { titulo: 'Que entendem a fome da tarde,', subtitulo: 'a roupa apertada, a segunda-feira que nunca chega.' },
    { titulo: 'E que estão encontrando', subtitulo: 'uma saída diferente. Juntas.' },
    { titulo: 'Você não precisa fazer isso sozinha.', subtitulo: 'Nunca precisou.' },
    { titulo: 'Comente BLINDADO', subtitulo: 'e entre para o Grupo VIP gratuito.', cta: true, pill: true },
  ],
},

{
  id: '26', tipo: 'cta',
  nome: 'Se você sente que perdeu o controle, leia isso',
  legenda: 'Essa sensação de que não adianta mais tentar...\n\nEla mente. ❤️\n\nComente BLINDADO. Existe um caminho.',
  hashtags: '#controle #esperanca #emagrecimentoblindado #grupovip #naodesista',
  cards: [
    { titulo: 'SE VOCÊ SENTE QUE PERDEU O CONTROLE,', subtitulo: 'leia isso.' },
    { titulo: 'Essa sensação de que nada funciona.', subtitulo: 'Que você já tentou tudo.' },
    { titulo: 'Que talvez não seja para você.', subtitulo: 'Que o seu corpo é diferente.' },
    { titulo: 'Que você não tem disciplina suficiente.', subtitulo: 'Que você é fraca demais para isso.' },
    { titulo: 'Essa sensação mente.', subtitulo: 'Completamente.' },
    { titulo: 'Você não perdeu o controle.', subtitulo: 'Você só nunca teve as ferramentas certas.' },
    { titulo: 'Não há fraqueza em não conseguir', subtitulo: 'fazer funcionar um método que nunca foi para o seu corpo.' },
    { titulo: 'O controle volta', subtitulo: 'quando você tem a estratégia certa para o seu momento.' },
    { titulo: 'Existe um caminho.', subtitulo: 'E está disponível para você agora.' },
    { titulo: 'Comente BLINDADO', subtitulo: 'e entre para o Grupo VIP gratuito.', cta: true, pill: true },
  ],
},

{
  id: '27', tipo: 'cta',
  nome: 'Se o espelho virou um inimigo, isso é para você',
  legenda: 'Quando foi que o espelho virou um inimigo? 💔\n\nVocê lembra quando se olhava e sorria?\n\nComente BLINDADO. É hora de mudar isso.',
  hashtags: '#espelho #imagemcorporal #emagrecimentoblindado #grupovip #autoestima',
  cards: [
    { titulo: 'SE O ESPELHO VIROU UM INIMIGO,', subtitulo: 'isso é para você.' },
    { titulo: 'Quando foi que se olhar no espelho', subtitulo: 'virou um momento de crítica e não de cuidado?' },
    { titulo: 'Você lembra quando era diferente?', subtitulo: 'Quando você se vestia sem drama?' },
    { titulo: 'Hoje você evita o espelho.', subtitulo: 'Ou se olha só para criticar.' },
    { titulo: 'Isso não é normal.', subtitulo: 'Mesmo que pareça.' },
    { titulo: 'Você merece se olhar', subtitulo: 'e enxergar uma mulher que merece cuidado.' },
    { titulo: 'Não uma versão perfeita.', subtitulo: 'A versão real. Com gentileza.' },
    { titulo: 'Isso começa antes da balança mudar.', subtitulo: 'Começa na sua relação com você mesma.' },
    { titulo: 'E há um caminho para isso.', subtitulo: 'Que não envolve punição.' },
    { titulo: 'Comente BLINDADO', subtitulo: 'e entre para o Grupo VIP gratuito.', cta: true, pill: true },
  ],
},

{
  id: '28', tipo: 'cta',
  nome: 'Se você está cansada de tentar sozinha, entre',
  legenda: 'Tentar sozinha exige força demais.\n\nExiste um caminho mais leve. ❤️\n\nComente BLINDADO e entre para o Grupo VIP.',
  hashtags: '#sozinha #apoio #emagrecimentoblindado #grupovip #cansada',
  cards: [
    { titulo: 'SE VOCÊ ESTÁ CANSADA', subtitulo: 'de tentar sozinha, isso é para você.' },
    { titulo: 'Você pesquisou tudo.', subtitulo: 'Comprou curso, seguiu influencer, tentou dieta nova.' },
    { titulo: 'Tentou de manhã cedo.', subtitulo: 'Tentou à noite. Tentou com academia, sem academia.' },
    { titulo: 'E continua sozinha com isso.', subtitulo: 'Com a frustração. Com o recomeço. Com a culpa.' },
    { titulo: 'Tentar sozinha exige força demais.', subtitulo: 'E esgota.' },
    { titulo: 'A transformação fica mais leve', subtitulo: 'quando você tem um caminho e não caminha sozinha.' },
    { titulo: 'No Grupo VIP você vai encontrar', subtitulo: 'método, suporte e mulheres no mesmo caminho.' },
    { titulo: 'Sem julgamento.', subtitulo: 'Sem dieta impossível. Sem solidão.' },
    { titulo: 'Você não precisa mais carregar isso sozinha.', subtitulo: 'Nunca precisou.' },
    { titulo: 'Comente BLINDADO', subtitulo: 'e entre para o Grupo VIP gratuito agora.', cta: true, pill: true },
  ],
},

{
  id: '29', tipo: 'cta',
  nome: 'Existe um jeito de recomeçar com direção',
  legenda: 'Recomeçar sem método é gastar energia sem chegar a lugar nenhum.\n\nMas recomeçar com direção muda tudo. ❤️\n\nComente BLINDADO.',
  hashtags: '#direcao #metodo #emagrecimentoblindado #grupovip #recomecar',
  cards: [
    { titulo: 'EXISTE UM JEITO DE RECOMEÇAR', subtitulo: 'com direção.' },
    { titulo: 'Recomeçar sem método', subtitulo: 'é gastar energia sem chegar a lugar nenhum.' },
    { titulo: 'É o hamster na roda.', subtitulo: 'Muito esforço. Pouco avanço.' },
    { titulo: 'A diferença não está em tentar mais.', subtitulo: 'Está em tentar diferente.' },
    { titulo: 'Com um caminho que considera', subtitulo: 'os seus hormônios, o seu estresse, o seu momento de vida.' },
    { titulo: 'Sem proibição extrema.', subtitulo: 'Sem fome que vira compulsão. Sem culpa.' },
    { titulo: 'Um recomeço com direção', subtitulo: 'se parece diferente de todos os outros.' },
    { titulo: 'Porque você não está repetindo', subtitulo: 'o que não funcionou. Você está fazendo diferente.' },
    { titulo: 'Esse recomeço está disponível para você.', subtitulo: 'Agora.' },
    { titulo: 'Comente BLINDADO', subtitulo: 'e entre para o Grupo VIP gratuito.', cta: true, pill: true },
  ],
},

{
  id: '30', tipo: 'cta',
  nome: 'Comente BLINDADO e venha para o Grupo VIP',
  legenda: 'Se você chegou até aqui, é porque esse conteúdo foi feito para você. ❤️\n\nNão existe acaso. O seu próximo passo está a um comentário de distância.\n\nComente BLINDADO agora.',
  hashtags: '#emagrecimentoblindado #grupovip #blindado #entrenogrupovip #transformacao',
  cards: [
    { titulo: 'VOCÊ CHEGOU ATÉ AQUI.', subtitulo: 'Isso não é acaso.' },
    { titulo: 'Esse conteúdo foi criado', subtitulo: 'para mulheres exatamente como você.' },
    { titulo: 'Que cansaram de recomeçar.', subtitulo: 'Que querem resultado sem punição.' },
    { titulo: 'Que merecem um método', subtitulo: 'feito para o corpo e o momento delas.' },
    { titulo: 'O Grupo VIP é gratuito.', subtitulo: 'E nele você vai encontrar o caminho que estava faltando.' },
    { titulo: 'Sem dieta maluca.', subtitulo: 'Sem passar fome. Sem mais segunda-feira.' },
    { titulo: 'Mulheres reais,', subtitulo: 'no mesmo caminho que você, com resultados reais.' },
    { titulo: 'Seu próximo passo', subtitulo: 'está a um comentário de distância.' },
    { titulo: 'Uma palavra.', subtitulo: 'Uma decisão. Uma mudança.' },
    { titulo: 'Comente BLINDADO', subtitulo: 'e entre para o Grupo VIP agora. ❤️', cta: true, pill: true },
  ],
},

]; // fim CARROSSEIS
